import Head from "next/head";
import Image from "next/image";
import HeroDestaque from "../components/home/destaque/HeroDestaque";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <HeroDestaque />
      </main>
    </div>
  );
}
