import Head from "next/head";
import Image from "next/image";
import SlideDestaque from "../components/home/destaque/SlideDestaque";
import TextDestaque from "../components/home/destaque/TextDestaque";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className=" relative content-center">
          <SlideDestaque />
        </div>
        <div className="absolute inset-0 flex md:w-full md:h-full bg-black bg-opacity-50 items-center justify-center">
          <TextDestaque />
        </div>
      </main>
    </div>
  );
}
